title: 5ls Docs
description: Docs
remote_theme: carlosperate/jekyll-theme-rtd

site_author: Patrick Haußmann
repo_url: "https://github.com/PatrickHaussmann/docs.5ls.de"
edit_on_github: false
logo: '/icon.png'
site_favicon: '/favicon.ico'
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: false
hljs_style: github-gist


## Specific to this theme
#site_author: Carlos Pereira Atencio
#repo_url: 'https://github.com/carlosperate/jekyll-theme-rtd'
#edit_on_github: true
#github_docs_folder: true
#logo: 'https://your.url/image.png'
#site_favicon: 'https://your.url/here.ico'
#sticky_navigation: true
#prev_next_buttons_location: None
#prev_next_buttons_location: top
#prev_next_buttons_location: bottom
#prev_next_buttons_location: both
#search_enabled: true
#google_analytics: UA-XXXXX-Y
#google_analytics_anonymize_ip: true
## The highlight.js library provides 79 different colours for their syntax highlighting. The default is github-gist.
#hljs_style: github-gist
